stakater/tekton-catalog

.github/workflows/pull_request.yaml
.github/workflows/push.yaml

Info :book: 
Invalid charts directory in gh action step publish helm chart. Changed from stakater to clustertask
Bug :bug: 
Fix paths-ignore

Update charts dir in push gh-action

---

clustertask/create-git-tag/Chart.yaml

Info :book: 
Trigger push pipeline to publish chart to helm repo stakater-charts

Trigger push pipeline to publish chart

---

clustertask/create-git-tag/Chart.yaml

Info :book:
Trigger push pipeline , Need to verify if the previous error in gh-actions is resolved

Trigger push pipeline

---

clustertask/buildah/.helmignore
clustertask/buildah/Chart.yaml
clustertask/buildah/README.md
clustertask/buildah/templates/_helpers.tpl
clustertask/buildah/templates/clustertask.yaml

Info :book: 
Add stakater-buildah task for building images

Add buildah task helm chart

---

clustertask/helm-push/.helmignore
clustertask/helm-push/Chart.yaml
clustertask/helm-push/README.md
clustertask/helm-push/templates/_helpers.tpl
clustertask/helm-push/templates/clustertask.yaml

Info :book:
Add helm chart for stakater-helm-push task

Add helm push task 

---

clustertask/comment-on-pr/.helmignore
clustertask/comment-on-pr/Chart.yaml
clustertask/comment-on-pr/README.md
clustertask/comment-on-pr/templates/_helpers.tpl
clustertask/comment-on-pr/templates/clustertask.yaml

Adding comment-on-pr task to the repo.
This task has ssh support

Add comment on pr task to repo

---

clustertask/github-update-cd-repo/.helmignore
clustertask/github-update-cd-repo/Chart.yaml
clustertask/github-update-cd-repo/README.md
clustertask/github-update-cd-repo/templates/_helpers.tpl
clustertask/github-update-cd-repo/templates/clustertask.yaml

Added new version of update cd repo task

Update cd repo task

---

clustertask/push-main-tag/templates/clustertask.yaml

Push main tag update

---

clustertask/push-main-tag/templates/clustertask.yaml

Fixing typo in task

---

clustertask/create-environment/CHANGELOG.md
clustertask/create-environment/Chart.yaml
clustertask/create-environment/README.md
clustertask/create-environment/templates/_helpers.tpl
clustertask/create-environment/templates/clustertask.yaml

[create-environment:clustertask] Add create environment

[create-environment:clustertask] Add create environment 

---

.github/workflows/stakater_build_image_flag.yaml
stakater-build-image-flag/README.md
stakater-build-image-flag/Tiltfile
stakater-build-image-flag/helm/.helmignore
stakater-build-image-flag/helm/Chart.yaml
stakater-build-image-flag/helm/templates/_helpers.tpl
stakater-build-image-flag/helm/templates/clustertask.yaml

- add build image flag ct
- update naming in other

add build image flag ct and fix other pipeline

---

.github/workflows/stakater_pr_cleaner.yaml
.github/workflows/stakater_trivy_scan.yaml
stakater-pr-cleaner/README.md
stakater-pr-cleaner/Tiltfile
stakater-pr-cleaner/helm/.helmignore
stakater-pr-cleaner/helm/Chart.yaml
stakater-pr-cleaner/helm/templates/_helpers.tpl
stakater-pr-cleaner/helm/templates/clustertask.yaml
stakater-trivy-scan/README.md
stakater-trivy-scan/Tiltfile
stakater-trivy-scan/helm/.helmignore
stakater-trivy-scan/helm/Chart.yaml
stakater-trivy-scan/helm/templates/_helpers.tpl
stakater-trivy-scan/helm/templates/clustertask.yaml

- add trivy ct
- add pr cleaner ct

add trivy and pr cleaner ct's

---

.github/workflows/stakater_cosign.yaml
stakater-cosign/README.md
stakater-cosign/Tiltfile
stakater-cosign/helm/.helmignore
stakater-cosign/helm/Chart.yaml
stakater-cosign/helm/templates/_helpers.tpl
stakater-cosign/helm/templates/clustertask.yaml

add cosign ct

---

.github/workflows/render_task.yaml
stakater-buildah/rendered/stakater-buildah-0.0.10.yaml
stakater-buildah/rendered/stakater-buildah-0.0.11.yaml
stakater-buildah/rendered/stakater-buildah-0.0.12.yaml
stakater-buildah/rendered/stakater-buildah-0.0.13.yaml
stakater-buildah/rendered/stakater-buildah-0.0.14.yaml
stakater-buildah/rendered/stakater-buildah-0.0.15.yaml
stakater-buildah/rendered/stakater-buildah-0.0.18.yaml
stakater-buildah/rendered/stakater-buildah-0.0.7.yaml
stakater-buildah/rendered/stakater-buildah-0.0.8.yaml
stakater-buildah/rendered/stakater-buildah-0.0.9.yaml

Edit github workflows and trigger pipeline

Edit github workflows and trigger pipeline [Squashed commits]

---

.github/workflows/stakater_build_image_flag.yaml
.github/workflows/stakater_buildah.yaml
.github/workflows/stakater_chekov-scan.yaml
.github/workflows/stakater_code_linting.yaml
.github/workflows/stakater_comment_on_pr.yaml
.github/workflows/stakater_cosign.yaml
.github/workflows/stakater_create_environment.yaml
.github/workflows/stakater_create_git_tag.yaml
.github/workflows/stakater_github_update_cd_repo.yaml
.github/workflows/stakater_gitlab_update_cd_repo.yaml
.github/workflows/stakater_helm_push.yaml
.github/workflows/stakater_kube_linting.yaml
.github/workflows/stakater_mvn_lint_code.yaml
.github/workflows/stakater_notify_slack.yaml
.github/workflows/stakater_pr_cleaner.yaml
.github/workflows/stakater_push_main_tag.yaml
.github/workflows/stakater_push_main_tag_bitbucket.yaml
.github/workflows/stakater_remove_environment.yaml
.github/workflows/stakater_rox_deployment_check.yaml
.github/workflows/stakater_rox_image_check.yaml
.github/workflows/stakater_rox_image_scan.yaml
.github/workflows/stakater_set_commit_status.yaml
.github/workflows/stakater_sonarqube_scan.yaml
.github/workflows/stakater_trivy_scan.yaml
.github/workflows/stakater_unit_test.yaml
.github/workflows/stakater_validate_environment.yaml

Removing workflow path from paths that trigger the pipeline
We do not want to create a new release when only the workflows are edited

Removing workflow path from paths that trigger the pipeline

---

stakater-fetch-pr-number/helm/templates/clustertask.yaml

We dont need url incase of bitbucket cloud but in case of bitbucket server

updating fetch pr numner task

---

stakater-helm-push/helm/templates/clustertask.yaml
stakater-sonarqube-scan/helm/templates/clustertask.yaml

fix secrets name for sonarqube and helm

fix secrets name

---

.github/workflows/render_task.yaml

enforce one job at a time 

---

.github/workflows/render_task.yaml

need to put variable in correct place

fix broken action pipeline

---

stakater-helm-push/helm/templates/clustertask.yaml
stakater-sonarqube-scan/helm/templates/clustertask.yaml

- fix param names
- fix step name

cosmetic updates in charts

---

stakater-push-main-tag/helm/templates/clustertask.yaml

Successful runs with ssh and basic auth
https://console-openshift-console.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/k8s/ns/chelsea-build/tekton.dev~v1beta1~PipelineRun/main-586bn
https://console-openshift-console.apps.tno1-ams.s9nghh76.lab.kubeapp.cloud/k8s/ns/chelsea-build/tekton.dev~v1beta1~PipelineRun/main-9p8p8

Remove the need to specify protocol param

---

.github/workflows/render_task.yaml

try to queue the jobs so, one works at a time

another take on concurrency

---

stakater-comment-on-pr/helm/templates/clustertask.yaml
stakater-create-environment/helm/templates/clustertask.yaml
stakater-github-update-cd-repo/helm/templates/clustertask.yaml

reverting for the sake of concurrency testing

reverting pipeline toolbox to test concurrency

---

stakater-create-environment/helm/templates/clustertask.yaml
stakater-github-update-cd-repo/helm/templates/clustertask.yaml

another try to test concurrency

---

stakater-rox-image-check/helm/templates/clustertask.yaml

Give option to ignore rhacs image check error

ignore rhacs error
